name: Commit

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: macos-10.15
    timeout-minutes: 15
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select Xcode 12.0.1"
        uses: devbotsxyz/xcode-select@master
        with:
          version: "12.0.0"

      - name: "Setup Carthage"
        run: carthage bootstrap --verbose --platform macOS

        #      - name: "Import Certificate: Development"
        #        uses: devbotsxyz/xcode-import-certificate@master
        #        with:
        #          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
        #          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
        #          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

        #      - name: "Build & Archive"
        #        uses: devbotsxyz/xcode-archive@master


